-- TRI AI BUBBLE INDEX — BANCO DE LEADS E ACESSOS
-- Cole este arquivo inteiro no SQL Editor do Supabase e clique em RUN.

create extension if not exists pgcrypto;

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  email text not null,
  phone text not null,
  marketing_consent boolean not null default false,
  source text,
  landing_page text,
  user_agent text,
  last_access_at timestamptz,
  access_count integer not null default 0
);

create index if not exists leads_email_idx on public.leads (lower(email));
create index if not exists leads_created_at_idx on public.leads (created_at desc);
create index if not exists leads_last_access_at_idx on public.leads (last_access_at desc);

create table if not exists public.access_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  lead_id uuid not null references public.leads(id) on delete cascade,
  page_path text,
  referrer text,
  user_agent text,
  screen_size text,
  timezone text
);

create index if not exists access_logs_lead_id_idx on public.access_logs (lead_id);
create index if not exists access_logs_created_at_idx on public.access_logs (created_at desc);

alter table public.leads enable row level security;
alter table public.access_logs enable row level security;

-- O visitante pode somente inserir o próprio cadastro e registrar acessos.
-- Leituras continuam bloqueadas no site público; você consulta tudo pelo painel autenticado do Supabase.
drop policy if exists "anon_insert_leads" on public.leads;
create policy "anon_insert_leads"
on public.leads for insert
to anon
with check (
  char_length(name) between 2 and 120
  and char_length(email) between 5 and 255
  and char_length(phone) between 10 and 30
  and marketing_consent = true
);

drop policy if exists "anon_insert_access_logs" on public.access_logs;
create policy "anon_insert_access_logs"
on public.access_logs for insert
to anon
with check (lead_id is not null);

create or replace function public.update_lead_access_stats()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.leads
     set last_access_at = new.created_at,
         access_count = access_count + 1,
         updated_at = now()
   where id = new.lead_id;
  return new;
end;
$$;

drop trigger if exists trg_update_lead_access_stats on public.access_logs;
create trigger trg_update_lead_access_stats
after insert on public.access_logs
for each row execute function public.update_lead_access_stats();

-- Visão pronta para exportação e abordagem comercial.
drop view if exists public.leads_comercial;
create view public.leads_comercial with (security_invoker = true) as
select
  l.created_at as data_cadastro,
  l.name as nome,
  l.email,
  l.phone as whatsapp,
  l.source as origem,
  l.last_access_at as ultimo_acesso,
  l.access_count as quantidade_acessos,
  case
    when l.access_count >= 10 then 'Quente'
    when l.access_count >= 4 then 'Engajado'
    else 'Novo'
  end as classificacao
from public.leads l
order by l.last_access_at desc nulls last, l.created_at desc;

-- Impede que visitantes consultem a visão por API pública.
revoke all on public.leads_comercial from anon, authenticated;
